// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: terminal/DmCall.proto
// Protobuf Java Version: 4.29.3

package cn.sanenen.dm.grpc.pkg.terminal.dm;

public final class DmCallPg {
  private DmCallPg() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      DmCallPg.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KeyValuePairOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KeyValuePair)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * <pre>
   * 键值对消息，用于表示参数或结果
   * </pre>
   *
   * Protobuf type {@code KeyValuePair}
   */
  public static final class KeyValuePair extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:KeyValuePair)
      KeyValuePairOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        KeyValuePair.class.getName());
    }
    // Use KeyValuePair.newBuilder() to construct.
    private KeyValuePair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private KeyValuePair() {
      key_ = "";
      value_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_KeyValuePair_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_KeyValuePair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.class, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object key_ = "";
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, key_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, key_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair)) {
        return super.equals(obj);
      }
      cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair other = (cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 键值对消息，用于表示参数或结果
     * </pre>
     *
     * Protobuf type {@code KeyValuePair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KeyValuePair)
        cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_KeyValuePair_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_KeyValuePair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.class, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder.class);
      }

      // Construct using cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = "";
        value_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_KeyValuePair_descriptor;
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair getDefaultInstanceForType() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.getDefaultInstance();
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair build() {
        cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair buildPartial() {
        cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair result = new cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair) {
          return mergeFrom((cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair other) {
        if (other == cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:KeyValuePair)
    }

    // @@protoc_insertion_point(class_scope:KeyValuePair)
    private static final cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair();
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KeyValuePair>
        PARSER = new com.google.protobuf.AbstractParser<KeyValuePair>() {
      @java.lang.Override
      public KeyValuePair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KeyValuePair> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValuePair> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DmCallRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DmCallRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 大漠对象id，不存在则创建新的
     * </pre>
     *
     * <code>string dm_instance_id = 2;</code>
     * @return The dmInstanceId.
     */
    java.lang.String getDmInstanceId();
    /**
     * <pre>
     * 大漠对象id，不存在则创建新的
     * </pre>
     *
     * <code>string dm_instance_id = 2;</code>
     * @return The bytes for dmInstanceId.
     */
    com.google.protobuf.ByteString
        getDmInstanceIdBytes();

    /**
     * <pre>
     * 要调用的方法名
     * </pre>
     *
     * <code>string method_name = 3;</code>
     * @return The methodName.
     */
    java.lang.String getMethodName();
    /**
     * <pre>
     * 要调用的方法名
     * </pre>
     *
     * <code>string method_name = 3;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <pre>
     * 不定个数的参数
     * </pre>
     *
     * <code>repeated .KeyValuePair params = 4;</code>
     */
    java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> 
        getParamsList();
    /**
     * <pre>
     * 不定个数的参数
     * </pre>
     *
     * <code>repeated .KeyValuePair params = 4;</code>
     */
    cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair getParams(int index);
    /**
     * <pre>
     * 不定个数的参数
     * </pre>
     *
     * <code>repeated .KeyValuePair params = 4;</code>
     */
    int getParamsCount();
    /**
     * <pre>
     * 不定个数的参数
     * </pre>
     *
     * <code>repeated .KeyValuePair params = 4;</code>
     */
    java.util.List<? extends cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder> 
        getParamsOrBuilderList();
    /**
     * <pre>
     * 不定个数的参数
     * </pre>
     *
     * <code>repeated .KeyValuePair params = 4;</code>
     */
    cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder getParamsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DmCallRequest}
   */
  public static final class DmCallRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DmCallRequest)
      DmCallRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        DmCallRequest.class.getName());
    }
    // Use DmCallRequest.newBuilder() to construct.
    private DmCallRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DmCallRequest() {
      dmInstanceId_ = "";
      methodName_ = "";
      params_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_DmCallRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_DmCallRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest.class, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest.Builder.class);
    }

    public static final int DM_INSTANCE_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dmInstanceId_ = "";
    /**
     * <pre>
     * 大漠对象id，不存在则创建新的
     * </pre>
     *
     * <code>string dm_instance_id = 2;</code>
     * @return The dmInstanceId.
     */
    @java.lang.Override
    public java.lang.String getDmInstanceId() {
      java.lang.Object ref = dmInstanceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dmInstanceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 大漠对象id，不存在则创建新的
     * </pre>
     *
     * <code>string dm_instance_id = 2;</code>
     * @return The bytes for dmInstanceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDmInstanceIdBytes() {
      java.lang.Object ref = dmInstanceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dmInstanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object methodName_ = "";
    /**
     * <pre>
     * 要调用的方法名
     * </pre>
     *
     * <code>string method_name = 3;</code>
     * @return The methodName.
     */
    @java.lang.Override
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 要调用的方法名
     * </pre>
     *
     * <code>string method_name = 3;</code>
     * @return The bytes for methodName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> params_;
    /**
     * <pre>
     * 不定个数的参数
     * </pre>
     *
     * <code>repeated .KeyValuePair params = 4;</code>
     */
    @java.lang.Override
    public java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> getParamsList() {
      return params_;
    }
    /**
     * <pre>
     * 不定个数的参数
     * </pre>
     *
     * <code>repeated .KeyValuePair params = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder> 
        getParamsOrBuilderList() {
      return params_;
    }
    /**
     * <pre>
     * 不定个数的参数
     * </pre>
     *
     * <code>repeated .KeyValuePair params = 4;</code>
     */
    @java.lang.Override
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <pre>
     * 不定个数的参数
     * </pre>
     *
     * <code>repeated .KeyValuePair params = 4;</code>
     */
    @java.lang.Override
    public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair getParams(int index) {
      return params_.get(index);
    }
    /**
     * <pre>
     * 不定个数的参数
     * </pre>
     *
     * <code>repeated .KeyValuePair params = 4;</code>
     */
    @java.lang.Override
    public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder getParamsOrBuilder(
        int index) {
      return params_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dmInstanceId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, dmInstanceId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, methodName_);
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeMessage(4, params_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dmInstanceId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, dmInstanceId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, methodName_);
      }
      for (int i = 0; i < params_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, params_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest)) {
        return super.equals(obj);
      }
      cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest other = (cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest) obj;

      if (!getDmInstanceId()
          .equals(other.getDmInstanceId())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParamsList()
          .equals(other.getParamsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DM_INSTANCE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDmInstanceId().hashCode();
      hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getParamsCount() > 0) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParamsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DmCallRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DmCallRequest)
        cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_DmCallRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_DmCallRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest.class, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest.Builder.class);
      }

      // Construct using cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        dmInstanceId_ = "";
        methodName_ = "";
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
        } else {
          params_ = null;
          paramsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_DmCallRequest_descriptor;
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest getDefaultInstanceForType() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest build() {
        cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest buildPartial() {
        cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest result = new cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest result) {
        if (paramsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            params_ = java.util.Collections.unmodifiableList(params_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
      }

      private void buildPartial0(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.dmInstanceId_ = dmInstanceId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.methodName_ = methodName_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest) {
          return mergeFrom((cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest other) {
        if (other == cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest.getDefaultInstance()) return this;
        if (!other.getDmInstanceId().isEmpty()) {
          dmInstanceId_ = other.dmInstanceId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (paramsBuilder_ == null) {
          if (!other.params_.isEmpty()) {
            if (params_.isEmpty()) {
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureParamsIsMutable();
              params_.addAll(other.params_);
            }
            onChanged();
          }
        } else {
          if (!other.params_.isEmpty()) {
            if (paramsBuilder_.isEmpty()) {
              paramsBuilder_.dispose();
              paramsBuilder_ = null;
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000004);
              paramsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getParamsFieldBuilder() : null;
            } else {
              paramsBuilder_.addAllMessages(other.params_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                dmInstanceId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 18
              case 26: {
                methodName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 26
              case 34: {
                cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair m =
                    input.readMessage(
                        cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.parser(),
                        extensionRegistry);
                if (paramsBuilder_ == null) {
                  ensureParamsIsMutable();
                  params_.add(m);
                } else {
                  paramsBuilder_.addMessage(m);
                }
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object dmInstanceId_ = "";
      /**
       * <pre>
       * 大漠对象id，不存在则创建新的
       * </pre>
       *
       * <code>string dm_instance_id = 2;</code>
       * @return The dmInstanceId.
       */
      public java.lang.String getDmInstanceId() {
        java.lang.Object ref = dmInstanceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dmInstanceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 大漠对象id，不存在则创建新的
       * </pre>
       *
       * <code>string dm_instance_id = 2;</code>
       * @return The bytes for dmInstanceId.
       */
      public com.google.protobuf.ByteString
          getDmInstanceIdBytes() {
        java.lang.Object ref = dmInstanceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dmInstanceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 大漠对象id，不存在则创建新的
       * </pre>
       *
       * <code>string dm_instance_id = 2;</code>
       * @param value The dmInstanceId to set.
       * @return This builder for chaining.
       */
      public Builder setDmInstanceId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dmInstanceId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 大漠对象id，不存在则创建新的
       * </pre>
       *
       * <code>string dm_instance_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDmInstanceId() {
        dmInstanceId_ = getDefaultInstance().getDmInstanceId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 大漠对象id，不存在则创建新的
       * </pre>
       *
       * <code>string dm_instance_id = 2;</code>
       * @param value The bytes for dmInstanceId to set.
       * @return This builder for chaining.
       */
      public Builder setDmInstanceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dmInstanceId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <pre>
       * 要调用的方法名
       * </pre>
       *
       * <code>string method_name = 3;</code>
       * @return The methodName.
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 要调用的方法名
       * </pre>
       *
       * <code>string method_name = 3;</code>
       * @return The bytes for methodName.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 要调用的方法名
       * </pre>
       *
       * <code>string method_name = 3;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        methodName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 要调用的方法名
       * </pre>
       *
       * <code>string method_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        methodName_ = getDefaultInstance().getMethodName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 要调用的方法名
       * </pre>
       *
       * <code>string method_name = 3;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        methodName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> params_ =
        java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          params_ = new java.util.ArrayList<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair>(params_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder> paramsBuilder_;

      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> getParamsList() {
        if (paramsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(params_);
        } else {
          return paramsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public int getParamsCount() {
        if (paramsBuilder_ == null) {
          return params_.size();
        } else {
          return paramsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair getParams(int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);
        } else {
          return paramsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public Builder setParams(
          int index, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.set(index, value);
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public Builder setParams(
          int index, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.set(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public Builder addParams(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public Builder addParams(
          int index, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(index, value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public Builder addParams(
          cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public Builder addParams(
          int index, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> values) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, params_);
          onChanged();
        } else {
          paramsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          paramsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public Builder removeParams(int index) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.remove(index);
          onChanged();
        } else {
          paramsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder getParamsBuilder(
          int index) {
        return getParamsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder getParamsOrBuilder(
          int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);  } else {
          return paramsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public java.util.List<? extends cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder> 
           getParamsOrBuilderList() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(params_);
        }
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder addParamsBuilder() {
        return getParamsFieldBuilder().addBuilder(
            cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.getDefaultInstance());
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder addParamsBuilder(
          int index) {
        return getParamsFieldBuilder().addBuilder(
            index, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.getDefaultInstance());
      }
      /**
       * <pre>
       * 不定个数的参数
       * </pre>
       *
       * <code>repeated .KeyValuePair params = 4;</code>
       */
      public java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder> 
           getParamsBuilderList() {
        return getParamsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder>(
                  params_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DmCallRequest)
    }

    // @@protoc_insertion_point(class_scope:DmCallRequest)
    private static final cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest();
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DmCallRequest>
        PARSER = new com.google.protobuf.AbstractParser<DmCallRequest>() {
      @java.lang.Override
      public DmCallRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DmCallRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DmCallRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DmCallResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DmCallResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 不定个数的响应结果
     * </pre>
     *
     * <code>repeated .KeyValuePair results = 4;</code>
     */
    java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> 
        getResultsList();
    /**
     * <pre>
     * 不定个数的响应结果
     * </pre>
     *
     * <code>repeated .KeyValuePair results = 4;</code>
     */
    cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair getResults(int index);
    /**
     * <pre>
     * 不定个数的响应结果
     * </pre>
     *
     * <code>repeated .KeyValuePair results = 4;</code>
     */
    int getResultsCount();
    /**
     * <pre>
     * 不定个数的响应结果
     * </pre>
     *
     * <code>repeated .KeyValuePair results = 4;</code>
     */
    java.util.List<? extends cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder> 
        getResultsOrBuilderList();
    /**
     * <pre>
     * 不定个数的响应结果
     * </pre>
     *
     * <code>repeated .KeyValuePair results = 4;</code>
     */
    cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder getResultsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DmCallResponse}
   */
  public static final class DmCallResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DmCallResponse)
      DmCallResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        DmCallResponse.class.getName());
    }
    // Use DmCallResponse.newBuilder() to construct.
    private DmCallResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DmCallResponse() {
      results_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_DmCallResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_DmCallResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse.class, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse.Builder.class);
    }

    public static final int RESULTS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> results_;
    /**
     * <pre>
     * 不定个数的响应结果
     * </pre>
     *
     * <code>repeated .KeyValuePair results = 4;</code>
     */
    @java.lang.Override
    public java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> getResultsList() {
      return results_;
    }
    /**
     * <pre>
     * 不定个数的响应结果
     * </pre>
     *
     * <code>repeated .KeyValuePair results = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder> 
        getResultsOrBuilderList() {
      return results_;
    }
    /**
     * <pre>
     * 不定个数的响应结果
     * </pre>
     *
     * <code>repeated .KeyValuePair results = 4;</code>
     */
    @java.lang.Override
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <pre>
     * 不定个数的响应结果
     * </pre>
     *
     * <code>repeated .KeyValuePair results = 4;</code>
     */
    @java.lang.Override
    public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair getResults(int index) {
      return results_.get(index);
    }
    /**
     * <pre>
     * 不定个数的响应结果
     * </pre>
     *
     * <code>repeated .KeyValuePair results = 4;</code>
     */
    @java.lang.Override
    public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(4, results_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, results_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse)) {
        return super.equals(obj);
      }
      cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse other = (cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse) obj;

      if (!getResultsList()
          .equals(other.getResultsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResultsCount() > 0) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DmCallResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DmCallResponse)
        cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_DmCallResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_DmCallResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse.class, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse.Builder.class);
      }

      // Construct using cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
        } else {
          results_ = null;
          resultsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.internal_static_DmCallResponse_descriptor;
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse getDefaultInstanceForType() {
        return cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse build() {
        cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse buildPartial() {
        cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse result = new cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse result) {
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            results_ = java.util.Collections.unmodifiableList(results_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.results_ = results_;
        } else {
          result.results_ = resultsBuilder_.build();
        }
      }

      private void buildPartial0(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse) {
          return mergeFrom((cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse other) {
        if (other == cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse.getDefaultInstance()) return this;
        if (resultsBuilder_ == null) {
          if (!other.results_.isEmpty()) {
            if (results_.isEmpty()) {
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultsIsMutable();
              results_.addAll(other.results_);
            }
            onChanged();
          }
        } else {
          if (!other.results_.isEmpty()) {
            if (resultsBuilder_.isEmpty()) {
              resultsBuilder_.dispose();
              resultsBuilder_ = null;
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResultsFieldBuilder() : null;
            } else {
              resultsBuilder_.addAllMessages(other.results_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 34: {
                cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair m =
                    input.readMessage(
                        cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.parser(),
                        extensionRegistry);
                if (resultsBuilder_ == null) {
                  ensureResultsIsMutable();
                  results_.add(m);
                } else {
                  resultsBuilder_.addMessage(m);
                }
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          results_ = new java.util.ArrayList<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair>(results_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder> resultsBuilder_;

      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> getResultsList() {
        if (resultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(results_);
        } else {
          return resultsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public int getResultsCount() {
        if (resultsBuilder_ == null) {
          return results_.size();
        } else {
          return resultsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair getResults(int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);
        } else {
          return resultsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public Builder setResults(
          int index, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.set(index, value);
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public Builder setResults(
          int index, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public Builder addResults(cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public Builder addResults(
          int index, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(index, value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public Builder addResults(
          cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public Builder addResults(
          int index, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public Builder addAllResults(
          java.lang.Iterable<? extends cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair> values) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, results_);
          onChanged();
        } else {
          resultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public Builder clearResults() {
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public Builder removeResults(int index) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.remove(index);
          onChanged();
        } else {
          resultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder getResultsBuilder(
          int index) {
        return getResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder getResultsOrBuilder(
          int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);  } else {
          return resultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public java.util.List<? extends cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder> 
           getResultsOrBuilderList() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(results_);
        }
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder addResultsBuilder() {
        return getResultsFieldBuilder().addBuilder(
            cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.getDefaultInstance());
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder addResultsBuilder(
          int index) {
        return getResultsFieldBuilder().addBuilder(
            index, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.getDefaultInstance());
      }
      /**
       * <pre>
       * 不定个数的响应结果
       * </pre>
       *
       * <code>repeated .KeyValuePair results = 4;</code>
       */
      public java.util.List<cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder> 
           getResultsBuilderList() {
        return getResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder> 
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePair.Builder, cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.KeyValuePairOrBuilder>(
                  results_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DmCallResponse)
    }

    // @@protoc_insertion_point(class_scope:DmCallResponse)
    private static final cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse();
    }

    public static cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DmCallResponse>
        PARSER = new com.google.protobuf.AbstractParser<DmCallResponse>() {
      @java.lang.Override
      public DmCallResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DmCallResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DmCallResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.sanenen.dm.grpc.pkg.terminal.dm.DmCallPg.DmCallResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyValuePair_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KeyValuePair_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DmCallRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DmCallRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DmCallResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DmCallResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025terminal/DmCall.proto\"*\n\014KeyValuePair\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"[\n\rDmCallReq" +
      "uest\022\026\n\016dm_instance_id\030\002 \001(\t\022\023\n\013method_n" +
      "ame\030\003 \001(\t\022\035\n\006params\030\004 \003(\0132\r.KeyValuePair" +
      "\"0\n\016DmCallResponse\022\036\n\007results\030\004 \003(\0132\r.Ke" +
      "yValuePair28\n\rDmCallService\022\'\n\004Call\022\016.Dm" +
      "CallRequest\032\017.DmCallResponseB0\n\"cn.sanen" +
      "en.dm.grpc.pkg.terminal.dmB\010DmCallPgP\000b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_KeyValuePair_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KeyValuePair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_KeyValuePair_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_DmCallRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DmCallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DmCallRequest_descriptor,
        new java.lang.String[] { "DmInstanceId", "MethodName", "Params", });
    internal_static_DmCallResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DmCallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DmCallResponse_descriptor,
        new java.lang.String[] { "Results", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
