// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client/Base.proto
// Protobuf Java Version: 4.29.3

package cn.sanenen.dm.grpc.pkg.client.base;

public final class BaseJavaPg {
  private BaseJavaPg() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      BaseJavaPg.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface getCurrentPIDResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:getCurrentPIDResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 pid = 1;</code>
     * @return The pid.
     */
    long getPid();
  }
  /**
   * <pre>
   * 定义请求和响应消息
   * </pre>
   *
   * Protobuf type {@code getCurrentPIDResponse}
   */
  public static final class getCurrentPIDResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:getCurrentPIDResponse)
      getCurrentPIDResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        getCurrentPIDResponse.class.getName());
    }
    // Use getCurrentPIDResponse.newBuilder() to construct.
    private getCurrentPIDResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private getCurrentPIDResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.internal_static_getCurrentPIDResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.internal_static_getCurrentPIDResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse.class, cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse.Builder.class);
    }

    public static final int PID_FIELD_NUMBER = 1;
    private long pid_ = 0L;
    /**
     * <code>int64 pid = 1;</code>
     * @return The pid.
     */
    @java.lang.Override
    public long getPid() {
      return pid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pid_ != 0L) {
        output.writeInt64(1, pid_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, pid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse)) {
        return super.equals(obj);
      }
      cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse other = (cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse) obj;

      if (getPid()
          != other.getPid()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPid());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义请求和响应消息
     * </pre>
     *
     * Protobuf type {@code getCurrentPIDResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:getCurrentPIDResponse)
        cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.internal_static_getCurrentPIDResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.internal_static_getCurrentPIDResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse.class, cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse.Builder.class);
      }

      // Construct using cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        pid_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.internal_static_getCurrentPIDResponse_descriptor;
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse getDefaultInstanceForType() {
        return cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse build() {
        cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse buildPartial() {
        cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse result = new cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.pid_ = pid_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse) {
          return mergeFrom((cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse other) {
        if (other == cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse.getDefaultInstance()) return this;
        if (other.getPid() != 0L) {
          setPid(other.getPid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                pid_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long pid_ ;
      /**
       * <code>int64 pid = 1;</code>
       * @return The pid.
       */
      @java.lang.Override
      public long getPid() {
        return pid_;
      }
      /**
       * <code>int64 pid = 1;</code>
       * @param value The pid to set.
       * @return This builder for chaining.
       */
      public Builder setPid(long value) {

        pid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 pid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pid_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:getCurrentPIDResponse)
    }

    // @@protoc_insertion_point(class_scope:getCurrentPIDResponse)
    private static final cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse();
    }

    public static cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<getCurrentPIDResponse>
        PARSER = new com.google.protobuf.AbstractParser<getCurrentPIDResponse>() {
      @java.lang.Override
      public getCurrentPIDResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<getCurrentPIDResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<getCurrentPIDResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.sanenen.dm.grpc.pkg.client.base.BaseJavaPg.getCurrentPIDResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getCurrentPIDResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_getCurrentPIDResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021client/Base.proto\032\033google/protobuf/emp" +
      "ty.proto\"$\n\025getCurrentPIDResponse\022\013\n\003pid" +
      "\030\001 \001(\0032R\n\017BaseJavaService\022?\n\rgetCurrentP" +
      "ID\022\026.google.protobuf.Empty\032\026.getCurrentP" +
      "IDResponseB2\n\"cn.sanenen.dm.grpc.pkg.cli" +
      "ent.baseB\nBaseJavaPgP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_getCurrentPIDResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_getCurrentPIDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_getCurrentPIDResponse_descriptor,
        new java.lang.String[] { "Pid", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
